### ISSUE TITLE
Add docs & examples for Flutter

### ISSUE THREAD

**Issue by deadsoul44** [firebase/emulators-codelab#6]
I am not sure if this is the right place for this issue but docs & examples for Flutter are definitely needed. For example, in the following page, there are examples for ios, android and web but there is nothing for Flutter. 

https://firebase.google.com/docs/emulator-suite

Thank you for the awesome work.

**Comment by samtstern** [comment]
@deadsoul44 thanks for the feedback!  The best place to file this would be here:
https://github.com/FirebaseExtended/flutterfire

FlutterFire has a brand new docs site and a page on using the emulator sounds like a good idea to me.  Right now we're not adding Flutter snippets to the main Firebase docs, although we do hear you and we know that people want it!
